sample_payload: 'sample_payload.json'
EXPT_DIR : "./log"
DATA_DIR : "./data"
IMAGEDATA_DIR : "./data/images/"
TRAINIMAGEDATA_DIR : "./data/images/train"
TESTIMAGEDATA_DIR : "./data/images/test"
WEIGHTS_DIR : "./weights"
exp_name: "test"

### TRAIN FUNCTION ARGS ###
train_epochs: 5
batch_size: 8
